---
title: "R26기술통계"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)



## 기술통계학

# 자료를 중심으로 통계수치, 표, 그래프 등을 이용해서 집단의 특성을 파악
# (중심경향-평균 / 흩어짐경향-분산)

# 중심화 경향
# 수집한 자료 전체를 대표하는 값이 무엇인지 나타내는 통계(대표값)
# => 최빈값/중앙값/평균



# 최빈값
# 수집한 데이터 중 가장 많이 나타난 데이터를 의미
# 주로 명목자료의 대표값 (중요!!!)
# R 에서는 table/prop.table 함수 이용

nums <- c(1,2,2,5,5,5,6,7,8,9,10,12,12)
freq <- table(nums)   # 빈도 측정
max(freq)             # 최고 빈도 확인

idx <- which.max(table(nums))   # 최고 빈도의 위치값 조사
names(freq[idx])                # 해당 위치값의 행이름



# 평균 
# 자료를 더해서 전체 자료 갯수로 나눈값 (양적자료의 대표값)
# 모집단이 정규분포를 띌때 가장 이상적인 중심화 경향 통계값
# R 에서는 mean 함수 이용

data <- c(7,7,2,3,7,6,9,10,8,9,9,10)
mean(data)   # 7.25


data <- c(7,7,2,3,7,6,9,10,8,9,1000)
mean(data)   # 97.09091




# 중앙값
# 관측값을 정렬한 후 가운데 있는 값 (중위수라고도 함)
# 데이터에 한/두개의 매우 큰/작은 값이 있는 경우,
# 산술평균 만으로는 데이터의 중심을 파악하기 어려움
# R 에서는 median 함수 이용

data <- c(7,7,2,3,7,6,9,10,8,9,9,10)   # 짝수개

sort(data)   # (7 + 8) / 2
median(data)


data <- c(7,7,2,3,7,6,9,10,8,9,10)   # 홀수개

sort(data)   # 7
median(data)


data <- c(7,7,2,3,7,6,9,10,8,9,1000)

sort(data)   # 7
median(data)





# 흩어짐 경향
# 데이터가 어떻게 분포되어 있는지를 설명하는 통계치
# 범위/사위분수/분산/표준편차

# 예) 어떤공원 호수의 수심이 평균 3미터
# 만약, 수심이 2.8미터 ~ 3.2미터 사이 => 뛰어들만 함
# 만약, 수심이 1미터 ~ 5미터 사이     => 뛰어들기에 위험




# 범위 : 자료의 최대값에서 최소값의 차이
# R 에서는 range 함수 이용

data <- c(7,7,2,3,7,6,9,10,8,9,10)
sort(data)

range(data)   # 2, 10


data <- c(1,2,2,3,4,3,5,5,7,2,2,0)
sort(data)

range(data)   # 0, 7


```



```{r setup, include=FALSE}

## 평균
## 중앙값

## 모분산
## 표본분산

# 표준편차








```










